services:
  - type: web
    name: amazon-affiliate-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: CHANNEL_ID # Naya environment variable
        sync: false
    healthCheckPath: /health
    autoDeploy: true
